services:
  etl_prod:
    build: .
    restart: "no"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: produccion
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: 1234
    command: ["python", "src/main.py"]
    volumes:
      - ./data:/app/data