services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432" # PUERTO_HOST:PUERTO_CONTENEDOR

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8978:8978" # PUERTO_HOST:PUERTO_CONTENEDOR
    environment:
      - CB_SERVER_PORT=8978
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
      - cloudbeaver_conf:/opt/cloudbeaver/conf

volumes:
  db_data:
  cloudbeaver_workspace:
  cloudbeaver_conf: