services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432" # PUERTO_HOST:PUERTO_CONTENEDOR
    environment:
      POSTGRES_PASSWORD: 1234
      
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8978:8978" # PUERTO_HOST:PUERTO_CONTENEDOR
    environment:
      - CB_SERVER_PORT=8978
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
      - cloudbeaver_conf:/opt/cloudbeaver/conf


  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: 1234
      MB_DB_HOST: db


volumes:
  db_data:
  cloudbeaver_workspace:
  cloudbeaver_conf: